triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: hi
states:
    timeout:
        component: meya.start_flow
        properties:
            flow: timeout
    first:
        component: meya.text
        properties:
            text: Hello, World!